; generated by PrusaSlicer 2.6.0+win64 on 2023-08-04 at 16:57:25 UTC


;
; thumbnail begin 160x120 10032
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAAdK0lEQVR4Ae2d2bcVRZbGzzv2Q71U1V
; rtk8/iU3Ut7dVvWr26u9pCq4tBGS+T4syk4KzgjIoD4ISI0FDaIrBUEJtR0L6A0C04MMgkw/K/iOYX
; 1HdW3LiZkZHDyXOu5sPmcu/JkxmZ8cW3x9zRGjlypMmSUaNGZcqMGTPMm2++aV599VXzwAMPmJtuus
; mMHj26sIwZM6YjwriS5LbbbjNLly41y5YtMy+88IKZNGlS6rG9JGPHjrXP++DBg+b8+fNm+/bt5p13
; 3jHjx4+PPkennnXMPLfKAg/hYnfddZd5/vnnzUsvvWQeffRRc/PNN/cM8GImAQCuWrXKvP3222bRok
; V2YnsJaCHhWc+ePdt8/fXX5uzZs2bv3r3miSeeMBMnTsx9rrqB2CoLPlbaI488YkWsd/fdd5tXXnnF
; TJ06tWvAyzN5jz/+uHnjjTfMtGnTzLhx4+xkLlmyxEyZMqUnAJbFgA8++KB57bXX7Pife+45c+TIEX
; P69Gm7mO688057j0XO3WkQgp1WUeBxgltvvdWyxe2335548pdfftnce++9QTbsBugkfX19ZsWKFZax
; fZU1efJkO/558+YVnsBOC+NnoaCCNUZ+oo127dplzp07Z7Zu3Woefvhhu7CKXqdqIPITzOzYsWMgAG
; PBx6pjYp5++ml7YyFw3X///VY1ow46AbwiD5RJuu+++8zKlSvtg0gDGPfG5GJWTJgwIXi+TovPerNm
; zTKvv/661TJJY8KGfeutt8yJEyfMsQM7zVsvPmZuueWWUoCvAnyM/ZlnnjHfffedOXny5CUAxgIPQS
; 1xAtTUmDFxhiYPCZXMyuRGygKwzEMEVIwFVRVjIzH5MD1Mw/jrAFsIhCwExv7UU08lgtMH6up7/sl8
; PaNlZeei0XbhlbVvi84bWmXDhg3WPNi9e7cdSysWeFx45syZ9uah/rzOBd/HMF64cKEFQd3AQ+644w
; 7Leiye0CSkTTzjZ+L5bjcAiKOErcp9ZAH11rF/Mkv6rmyDT/J/j//OEghgKPs8Y+eNMaEJDxw4YJ2k
; 5cuX23vgHFEAhCkw1DF2xWBFnQsuTKgGVqkLeAAGcwEWS3rwsQDgPDhYnAd1VhfwsE8fe+wxa5Py/6
; zjZ4wbYT6/Zdgg8EkOz7vcfPjqfHPPPfcEGbQKIIIdwkKYAocPH7b3AYHp81aWo4GNhKPBA8/LemmD
; ggFffPFFa18xqZ0CHoJniKPB4pGjURYQPEBihQ899FDH2RDzBdZDXcUAb0nf8FTg+bJ3ySQLiJB9Wx
; SI/A7A9+zZY+OT69atsxrUn+9UAMoAR2XypSqA5w+Qh8qqhpWqBh4TAuhYfbCtVnpVwOD54IjB5gCy
; auBxfiIIOBrY3WVZL00O3Xe5WbNolk0kVMWGLPTFixebY8eOmePHj1sndPr06Yls2UpiPVgD1gPBVQ
; MvyTDFKcCr4wFUAUBWNHEx7DU5GlUDRMKDJYMiu7KKczJmJhCzJ+aceVgvTT5/4ZKdViZcg6ApN2/e
; bM6cOWO2bdtmFxGATJv/AQDkZubMmWOeffbZQWGTToDPNVJRBRjHZdQB52HR4GjwU45Gp8AnYcyMn0
; UbY6OlCePF00blipGyWK8K8LXZcOE/WLZKC+2EhLETTyUbA/hIaSrEFZr7NgCJG+HloVb4oA7g+TfB
; Q8fAD8XmQg9AqUBUYh3A88FD1oHx463mZUNA/OSTT1rbEhbKOn7ehGsLqdwswUHZuOyhzEiBKzzvtW
; vX2rgeni6Bb81BFgZa/MODI7yC6q2D9UI3w8NnLEnZiSTGQ7DxsPVYPFIhdYNPgGMhM37UJ2PRZ0mi
; 76K2KOTQpIfAWzXrpcmBRX+09n8oVsp45s6da/r7+82FCxcsCF3N49uGiQAEragPDuoG66XdmPKxLA
; qfDd2JZ+xE/LHF6gBZlnAswGNiGD/qLO04FhiOHo4GjJF17tvG39AR1gux4fuL723HHd05AJioWZyM
; o0ePWvOJuQrNayIAOXm3WS9E7XiZeMs+s/EZAc0FCxa07ca6wZYlTAjjh5n9z3RvEEDMuZZOHl4b8H
; z54qVxNuQk+xYTibIvgso4HCy22PKvQQDsNPiKAM9nO24e+w71xmTgKOFoqNKjVwCXJCwOxk/cE9Zg
; IaGmcDRQvTGs959Tr+ga+Nps+MTvzfLFC6yNSh731KlTNnqBveuzYx4Qtkb3GOslqVqEyYLyYT0ms2
; zsrZOgSxI0DeVRqGUVcWR956lJ13QdeL78+N+vmG+++cbGWMsU7UYDsNvAk0D77777rp1EVdf0Ouhc
; YfxkZIgZEuYKARDW66bKzRLCNdyDPN0yIGz1EvjSQEN4AvYjI8DEkdJhIgnb8Hmvgg5RwS72HozB74
; xf+eQk8NXpaBRWyRcdlHWvzLe58bwq2JUW9gjA6UXw4UHCGhjqfoAXBiSNhxeZFPztNvAQxo+HqwyD
; +xmLiZglqozPep310qT/1YlRIbNUAPJlXGh+KQq+TrAek4bKlZEbOg4gMqFiw24Dj8kgBaUy/7TjcF
; BYQG+9+Lj55JbfDinguXLovr+3Doqbc48GIADCPkFFoBK6DT4mBXXLokBlxdh2TDIqjXyysgjdAh9j
; xkkiqxTjaCydfNWQAltIdj1/k5k/f36ufHLbBmTVMul6uaiT4EsDEnlQwisASWwWa99x00TuBdy6gc
; f1CQuR0cDjzQLfUFW5mbLgdzYnHvtCV0sql59MKhkI4jtu0WCnwaf0G9elOiYP8Hxh8nFQYkBQBeik
; SmE8KlhYyPw9JLdPGBqORlHBQdmw9ME2kWSqYF9UIkWEO4kNq2Q91D55XGy5mEqSGGAACNQg9i3/rw
; JoaaI8LjZfDPB+Tio3S/Yvm2wzVaF8ciuN4XjwRPBVnVE163F+1D1xvZjy9iKgARSwIXniqgAn1mOx
; sGhwNBQe+iWzXogN//rCnNQKp1aWmnVLpKoCn14Z1Nv7VQLPF0IhjJ98MqApCjpXME/QEBRCxBz/S2
; K9NNmzeFw75BQNQAkTRzAYIz+Pm50EKGxMwisEMJn4ToLPBRdgIYPiVp3kAR3CcyBuisplYTYqN58c
; Wvh7aye7VTOZAJQNCCB4+IRrsipm0xwNLh6Tx60KeD4I1YAI8EuVxoIPpsbDVtVz1vHzJ/7hF6lysw
; SV/PEbj1r/guefqYJ9ATwACfsniQ2TAMXE42jIUK8bfC7QAA8eN2yucE0WmBg/rKc4Y8N6xeWLKS2z
; fvrlZt++fVartvKAT8KDBoDYQa6HkwQmJpp0lApLu8F8SYIpQMA7pErxoHGUOI6F1zga5cE3+8arLA
; F8//33tkNCKy/4XLDhvWLg6wVnV/AM1fiHiewV4LlCuEnNfRij+xlmBm/WqRCzYb1y8vbIYWbqv1zZ
; xg5B+507dxYHoISJI9ZDjZucCiqAcTTketcJvhjg+Y4F3hlmBaDjfmBHFYzGsN7H038zpMBQp8B6L4
; 8YZsaPGjHIZEN7tsqAT8LEg2hUFeEVKDYmj9tN4PmCKiYmia1HrZvPiEnSsF5Y3h87zEz71+ED5jwY
; B8wLPPfEeJarV6+2uVxV/A4V8MGCpO5YPHj5asDUqNxiAuuhcsV6viQCsCj4AADhCSYOu4/JRAWrEV
; AnwVcWeAhqABOCki69s8Figs0BpW//NY5GNvhmjhgeJB8XQ60y4PMb/7gXUcsKxXt6EXzYeLAeC8YH
; GiYEBaN4wQCzYb1s4MF6vspNE5432GgVsfk4Ad6h2/gnSbCj8ILJQITSYHUDj3FRt4a9h+MRUs0cR8
; Honhl/N6QAUTf4Flz/61SV6wvkxMJGc+YGIGxAXI8gYkzjH0CjEim84m6DD9sOdYvajcloNKwXljys
; xxzyPgxNo9TaLhqAnIAvu41/Yi4qQaWBeHVI7YajoTwuCyHr+EblhkUqd8LoG6LmH3+AeKua2ssWjA
; IgAKAsq0jjHwGI/zOxbsuNusAHU+OZcw/xedzLhhQg6hScsFk3DB8wt6H5J0QH8VD95CYlogCoxj9J
; 7TFiweeLmpYnvS1WNfiI7+Fo0E0hO6Nxo1k2pWG9NBHrTfrzdYPmKWn+Wfg4eIS1IJ4kb7gVUrmUMK
; GyYvK4seCTqGUF9ljaOxxlgKfzY69C/1nqGfA1rBcGn8t6IQDyO8QFftA8aR1eUwGImiUrQIuxoo1/
; YtWrSqSwz1w2LAM+bphz4mmFWI/PkIb1wiJHIzSPNzvhFdgO4KHhQip6EAD5IyVTOBpuS65OgU8CA+
; JVM+gYGy0EKG4e1mYFxrBek8dNF9fRiJlHTCuaCKByQ+E5V9oAZFJQh3gpajqTF3hFwCeRlwpzZYEn
; SRgzYyePG8N6T/f945ACQ92yqW9YUOX6phLZI5wMtGaeNsUWgLjFOBoY6pywKPjKAFCCvUbVdJb6dA
; GlPK4qnbNYr1G56QLrrbr5V2bhQ/dGJQ8w17QdW5HwXAvVB+v4G7h0A3yyAZWp0I6VaYDCy8LQ5TgY
; sHE0yoMP1stqoCSBuFSKV7RdXgtPkQnqBfD5giqmKABm9j/DM6dmT+8Th8DXsF428JIcDWkjYUR/hy
; DwFTB33O6vhQAYKjaoC4Ah8GibMOw7/u83/slS0Y2jkQ2+Bdf/JtXRUD5cXSt45phHgM9/37oSAPYK
; +/nqE/uO0BBxPYzdGPuwYb2wwHrT/+2qAc8sbX4Il1HljrlGgUnSsUMSgFkgcgFI6RfvaWC3hgBIHr
; cBX7q44RX/2Y1NcQyVNODVBb2aWjkAe5H9ULvawAXbQ/YHKzFJBV8qGG0cjTS5lMe9KvV5+3NDhAFH
; gzlQlThdzHj+2pCnFACL5HjrYj+cEMIrFC76n2F/4KVhn1zycJvqlZCI9fr+4w/BZ665IaqgPK6evz
; t3iruqPUlhALpbIPQKANU5NKvxD+yIQfz6okfM7lsb1guBb+6/XxFl7mjhAywcjVDVkhxChcsKq2C9
; 3wu15kFyJ8CHvcH7Jeo73Dga5STJ0QjZ2oS8qNv0Qy8hUYdatGleJmy5NX8EFKnbynqRvBMAVPCzaf
; xTjYQcjSRRHhe16tt2WQIW1EWCuGEsfgYUI+iP2pI+K5lcBnwuAPk/qhS6x95oGv+Ul0t53HjWY87V
; /Yy5KDKfwgTZEXWojQag/0HWFghVsJ9+qvEP7NewXjnJy3puHleNl4rOqY8ftCnx2pBKTgWgAMbgKM
; NPMjDLMqAom9WSlccV+BrWC4MvlvXs8/xbHhd7T45emfn08cH5lE9OK2gOAlCStAVCGQDK3iCgDMM2
; rFde8jgasJPyuHolwjWHqgKgBKcSElM7Pxd8UQAU2LAPoFW11C0ySL2MTHiFOF4M+Jo8brq4edwY8P
; HMiS7gaPg1l50An0T9tNXOLzcAJe4WCHkHiZolm4GxG/OwGtYLy/tjL8sVXtH7uHrNwj+mkwCUAHq3
; nZ8FYOyXJQweIGG/yd3OUrn+Bi6Nyi0uKhh98pF5UU0zse9oncKchQp26wAggPPb+eUGoAAXswWCLo
; YNoP06GkejHPhwNBQ6SWugJNbT+7gqGO0m+FwQ8j2SHiQcCgMQYXVBqYDRr47AeYH1lGt2GbFhvfzA
; e3vkZWbKn64Z8Nwwa6hOUQMl9+/kcbH1tD1FaOHXCUDX/rMNKssAUICSYcsqg+m4eer2tIOlf3zDev
; nAh6MxccyNqfYdz1ubTRJXBZAE9WMcvW6Br+2ElAWghLgSBaPLly8P7hTZOBrxAuvhaMRkhwAfBaNE
; GJROzfrOzwaA3Ag6HdbDLlTnrLSBNyo3LFK5sF4M+Iirals1shrakKfXwVcagPyflYZ7jwrWTfFyuP
; t+rzvweROua1RuQCimZSsDvb88LiO8ovdxEWWUlI/ls7RzlAFfVQBkHIUAKBACMG3g4g+QFYiDQgAS
; kP5s98etSMR6k//yz1Hgc/O4SY2XeOaQAlGIpA15ug0+MiR454UAyM1C+YQBQptDc6PEoJqC0Wzwua
; yX1dkBRwNgkU4LdXhFACfzlKSNugFAvk8gmoXDAsoNQJALvavDZUga1ssW19HIAh92NalMgKe+3DGO
; hjbkkTbqFvi4NpXW+AhkZhh/NAC5OKpWedwY8H00rcnjponvaGSBSX2VUasxBbtJQsEpcUMAWSf4+M
; mYCQ0xBtiY80U7ISCXL+NsaCChgTasF5ZNfZflUrnK42r38SLgk/pl8tFgqr/sJAABmAoRYG3YW42v
; oooRLJNdtDdgPdI6/meNys0neVlPfZUJr0hllQGfxHYHu+gAoApDNnxZ9sM+pd4Qtas6gEFhmDQAMk
; i+SGV0UlV0Evia8EoYfHnCK0wYAWW3YLQK8LlCmCbp/d6y4OOahOJwNHhtVgXNiXHAJACCXFiPFE+W
; XdiwXjbw8mQ0YCTyt5g8SRvoVAU+iTbkwalMclDygo/zKS6Jt8v4bwr0IG8DUC4yhQXK42ZdrGG9bP
; DFFowyUXofF/DF7NRZFnyuqAER5FMEgBwLa+Mk4aHLUQ2Bb8BbcaCfV+ooWIy58JK+hvVCItaLAYrb
; Vzn2feiqgOeKXr9QO7xY8KkhPOPnu+4m5pkA5AQ4GKhcXOWsi80YN6IBX0BgvdVjf2Ueu3927jwu+f
; Q6WS9JOIeC3DHdMmA6jmXhYEsmORpBAGLoYizGsN68Cdc2KjcgavwDIxByUMFuGusBOGylrILRusDn
; Cvlk2FDbqyU5GphrqjnUzqh5wMdGmS2Cy/piw3rFJK3xDyqNOj01UHIdDf7G5AHUsiq3SvD5kRDGqH
; 7d+rvyuJAXiyjL0UgDnwWg+8c08DWsFwZf6H1c7CFlIGA5zBwcDcIrMR1e62S9NOcC+5SFhJNEPFJ5
; XL3vmxd80QBsWC8sse/jSt2yo7zy6L3EejHmF175Bx980N72zH+9sgj4BgGwnbe7yHqrp1wxpMBQpx
; Rt/ENQn5hb2Q15qgReFvj4HObD0dAev7C5n1IrAj4LQHU51wFPTbq6UbkBydv4h2CsGv8waTgoqLEi
; G/LUCTzZgNiqbh5XbIhKVnq2KPgsAH/44QdLq3f1/eWiyr1ySIGhTsnLehjq2EmEV9TWxBUC/TAJzN
; jJt9aKgk95XOLCAI1xSEMqaaECiRgnJAl8FoBbt241586dM1tv/+2QAkTd4Cvb+CdJYENASrgjaUfP
; TgAvC3xclwXDwmFsANH93DfX1M4PVswLPgtA0M3bbPu2/NV8MGpoAaMO4BVt/OOHXkKiDXnwNrsFPA
; QVi6mgglG/0WQawDgO+1bNjmLB13ZClEDe9ekGs2HO1UMKJJ0EX5HGP9opMpYtBTjAC2uqSWed4ONz
; WJuYHx66tueKAZ/Lhiw6hZtiwDfAC+aCuNfvvfee2fH6LLN90tACTJWSt68yKgt7iPheXu/WBQm/p2
; 2B0CnwwV4UD2AuuI5GHvC5gsrGQVEDomgASgguUpRw4Iut5sNplw8p4FTBenkcjdjGP3ltOxjE3wKh
; EypXeVyuAwNyrTLgc9kQNmdRsiBzARBhIFTibt68+RfDhnkdjdjGP0UB5G6B4JdIlQUeY4LtyGgQhk
; sqvSsCPF/twuKwIdmf1DBMCMUqx+/fvOZn66CI9fzGP2niNv4BIFUBLk38LRDKgo/FAjOxePTieifA
; J+F5AHS9Rel+Nnr06HQAuh4OsaCtH/+X2TD3atM/dWgBLAt8c/5YfAOXqsGWJv4WCEWAxzHYl4DBLR
; jtJPhcwb+g4BW2FfiiACg2xC0nl7n9tZnmk7FDC2hJkrQ/bkgdqmA0zwYuVYtabqD+Y4EnRwMAM37u
; Q3ncKoAXAz4J2gMQMga+Fw1ACeglTNC/Y7NZP0TDNW7BaMyeGNyztjOTod4N8Als7hYISU6Dz3qwNn
; MGAFUwWhfrpQnZH7SIfTE970W5AWygjRs3mp1vzB5SDsqlPO5wew+ETtIaKCEKiegFm6IbuFQNQDkR
; aCQM/LQtENQ3EPC5BaN1s55v80kwAWDDVpGLM3i94PzlJ6t73kGRozHpz9cNmFAMch6C37LCdTQ6nZ
; 3IAzxfABWBX8bvHsffiesRCkFdK1fbK+CTcK5WmYFwY1D75vVrzNp7rulJB+VSeCXd1lPICQOfcAdv
; duFooOaSOrz2AvB8piMDQSqM8RIAZuHwNz+P2w3gpYGv7YRwQJlB8aBgCYoV+9cv6Sk2zONoEKtatW
; qVfSVVFSq9Cro0D3f9+vXttht+eKXMHFfJeokALANCbhQ749ixY+ann34yh/btMhvnXtN11nt5xKWM
; RsykY0cRmoA5yGrAfrEtK7oFOhd8LB6cJJibn2oWWgXwOgm+AQAsAkIoHmfk9OnTZvfu3dYWQWDDbm
; VQ3h87LKhyffWrglHlcfk7dhNMojfCeglwvvrFfMCjRAupQyrjV9PyXlO5rnBsy/9yrNqFMQ4ePGjO
; nj1ry7kUm+LB4OFQev6/X243m2+rJ5/s5nFjQOB2GCUj4H+uF/VRxzEb8tQBOFdgbeVxkxr/4LXDhI
; w/LxN2GngIi4fxt9JOljYwVtnKlSvNiRMnzOHDh22WBOM3STUTP9uyZUvH2RDwzRwxfJBqShMVjJKS
; AoihYwlhaMfHbgDNF4BGViGm8Q9jIl0IG6pEqhfAB1mxOGDoVuik7qD4iXG7Z88ec/78ebNu3bp2qX
; nazfBgWJ2U/O/9dG3lDopYD0cjZvJgMhWM8jOWwbQhDwn8rOBvJyVv4x+J23KjauDlAR/XgbH1VuCo
; UaPCAJRwMCoVR+P48eN29aFmYykddUDye/umdTafXBX4Flz/azN+1IjMiQNEKhhVHjfv5HMONQ6KaV
; lRpXDtIo1/XGHhqMOqSxp1AA/hmfPsYD++C/iiAAhNfvrpp+bHH38027Zta2/LlefmpQ4wlNesWWPI
; J5dRyXlYT1kD1C32UFlViccJm7g2b6eE5wZrM243j5v32bsSUyJVtaOBqaC3AgW8TADycGGMQ4cOmT
; NnzrS9Qj2YooI6g0H3fb7FbJl/dW7WA3wxrIeQEVB4RWOvQgA1q1lbn3YCePxk8XMdNf7Jy3ppqpYx
; A2gYPS8I87Aei0UeOvfjgy8VgBisa9euNSdPnjRfffWV1dmgN805yStMIB7oRx99FJ1P5l1l39HIUl
; msOuylToAEUT4ZoFQJPp5P2cY/aeCTcD40A6lIzl8l8BBlZFC9/J4EvkEAZJAYqv39/ebChQtWXSpE
; keagFBWpM94G+59AwatYb+KN10ZNIKtOHUa18jopLFZUGrnjog6K+0zU+AcvXe3aqgJdGtlg3/PMqg
; AfWGHR6w25NOANACBfhCUAA07GkSNHrM1EoDnrBsoCUb2oP9v43qB8clJ4JSQqGFUet9PgcxkXVU/c
; kAnNAzoJ52CxV9H4JwZ4vrnFNSlsADRFWY/nL3MnxHqDAIh9sX37dhtU3rRpU7sCJM9NlGVDHj7xxR
; 1rnrdsyK7gvJmWdKwvjFUFo35lSJ2Cd4qDIq2h8Wbdv7+BC7/XAbwkhxM2x3zJA0CuywKUTRwDvDYA
; Ybpvv/3W2ntUVIDiMjdSBoiwByD6YtvH5tD+PTbWmBTkdsGoglG9j9sN4LmsBvAAkmzPrIWnglF/A5
; c6gecyHosZ9c/4OW8W+DAZGD82H8fHAm/kyJFWWqdOnTJffvmltWF4YFXcSBkgKnr/4Ycf2oD3/v37
; 2y/k+JOnglFWXpatVBXAYkRjgw21KPxjGK/f+KcboEtiOs5NmElNy9PCK/gL1B0CwjysJ/BZAK5Ysc
; JSrov2qm6sDBBRZzDy0aNHrV3Krpx6l4GfKhhF3eUBR52ifDIFA+4CgbUVBknbwKXToItRsdpxE7PG
; PZ7xMn4RQxHgtQGI2ktDeLeByI2iXj/77DNrn+7atcuyBqyH6VC0R12dwuKA0fE0WVSwBpPKAoI56g
; ZdDPB8NmT8kAELXy08YPZYRyMNfBaAWQOo+ubzgpEJhCVgakAIG1I4Gjt5vSI4epgVakKUlU3qxHPP
; 69X6Hi7jB4hJGY28wJP8P+E9Mk8oUr6dAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.65mm
; perimeters extrusion width = 0.65mm
; infill extrusion width = 0.65mm
; solid infill extrusion width = 0.65mm
; top infill extrusion width = 0.60mm
; first layer extrusion width = 0.65mm

M73 P0 R1
M73 Q0 S1
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.6 ; nozzle diameter check
M115 U3.12.2 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling

G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line

G92 E0
M221 S95
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.04 ; Filament gcode LA 1.5
M900 K18 ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P4 R1
M73 Q4 S1
G1 E-.8 F2100
M73 P7 R1
M73 Q7 S1
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.2
G1 X97.785 Y96.125 F10800
G1 Z.2 F720
M73 P8 R1
M73 Q8 S1
G1 E.8 F1500
M204 S800
;TYPE:Skirt/Brim
;WIDTH:0.65
G1 F1200
G1 X98.844 Y95.163 E.07222
G1 X100 Y94.893 E.05992
M73 Q9 S1
G1 X150 Y94.893 E2.52394
G1 X151.375 Y95.285 E.07217
M73 P11 R1
M73 Q12 S1
G1 X152.337 Y96.344 E.07222
G1 X152.607 Y97.5 E.05992
G1 X152.607 Y112.5 E.75718
G1 X152.215 Y113.875 E.07217
M73 P12 R1
M73 Q13 S1
G1 X151.156 Y114.837 E.07222
G1 X150 Y115.107 E.05992
M73 P13 R1
G1 X100 Y115.107 E2.52394
G1 X98.625 Y114.715 E.07217
M73 P16 R1
M73 Q16 S1
G1 X97.663 Y113.656 E.07222
G1 X97.393 Y112.5 E.05992
G1 X97.393 Y97.5 E.75718
G1 X97.761 Y96.211 E.06767
M204 S1000
; printing object Shape-Box id:0 copy 0
;WIPE_START
M73 P17 R1
M73 Q17 S1
G1 F8640
G1 X98.844 Y95.163 E-.34798
G1 X100 Y94.893 E-.27411
G1 X100.77 Y94.893 E-.17791
;WIPE_END
G1 Z.6 F720
G1 X148.868 Y111.368 F10800
G1 Z.2 F720
M73 P18 R1
M73 Q18 S1
G1 E.8 F1500
M204 S800
;TYPE:Perimeter
;WIDTH:0.649999
G1 F1200
G1 X101.132 Y111.368 E2.40966
G1 X101.132 Y98.632 E.6429
M73 P21 R1
M73 Q21 S1
G1 X148.868 Y98.632 E2.40966
M73 Q22 S1
G1 X148.868 Y111.278 E.63836
M204 S1000
M73 P24 R1
M73 Q25 S1
G1 X149.475 Y111.975 F10800
M204 S800
;TYPE:External perimeter
M73 P25 R1
G1 F1200
M73 Q26 S1
G1 X100.525 Y111.975 E2.47094
G1 X100.525 Y98.025 E.70418
M73 P28 R1
M73 Q28 S1
G1 X149.475 Y98.025 E2.47094
M73 P29 R0
M73 Q29 S0
G1 X149.475 Y111.885 E.69964
M204 S1000
M73 P32 R0
M73 Q32 S0
G1 X148.878 Y111.92 F10800
;WIPE_START
M73 P33 R0
M73 Q33 S0
G1 F8640
G1 X146.01 Y111.891 E-.8
;WIPE_END
G1 Z.6 F720
G1 X147.39 Y98.875 F10800
G1 Z.2 F720
M73 Q34 S0
G1 E.8 F1500
M204 S800
;TYPE:Solid infill
;WIDTH:0.653919
G1 F1200
G1 X148.352 Y99.837 E.06912
G1 X148.352 Y100.701 E.0439
G1 X146.799 Y99.148 E.11158
G1 X145.935 Y99.148 E.0439
M73 P34 R0
G1 X148.352 Y101.565 E.17366
G1 X148.352 Y102.429 E.0439
G1 X145.071 Y99.148 E.23574
G1 X144.206 Y99.148 E.04395
M73 Q35 S0
G1 X148.352 Y103.294 E.29789
G1 X148.352 Y104.158 E.0439
M73 P35 R0
G1 X143.342 Y99.148 E.35996
G1 X142.478 Y99.148 E.0439
M73 Q36 S0
G1 X148.352 Y105.022 E.42204
G1 X148.352 Y105.886 E.0439
M73 P36 R0
G1 X141.614 Y99.148 E.48412
G1 X140.75 Y99.148 E.0439
M73 Q37 S0
G1 X148.352 Y106.75 E.54619
G1 X148.352 Y107.614 E.0439
M73 P37 R0
G1 X139.886 Y99.148 E.60827
G1 X139.022 Y99.148 E.0439
M73 P38 R0
M73 Q38 S0
G1 X148.352 Y108.478 E.67035
G1 X148.352 Y109.342 E.0439
M73 P39 R0
M73 Q39 S0
G1 X138.158 Y99.148 E.73243
G1 X137.294 Y99.148 E.0439
M73 P40 R0
M73 Q40 S0
G1 X148.352 Y110.206 E.7945
G1 X148.352 Y110.852 E.03282
M73 P41 R0
M73 Q41 S0
G1 X148.134 Y110.852 E.01108
G1 X136.43 Y99.148 E.84092
G1 X135.566 Y99.148 E.0439
M73 P42 R0
M73 Q42 S0
G1 X147.269 Y110.852 E.84088
G1 X146.405 Y110.852 E.0439
M73 P43 R0
M73 Q43 S0
G1 X134.702 Y99.148 E.84088
G1 X133.837 Y99.148 E.04395
M73 P44 R0
M73 Q44 S0
G1 X145.541 Y110.852 E.84092
G1 X144.677 Y110.852 E.0439
M73 P45 R0
M73 Q45 S0
G1 X132.973 Y99.148 E.84092
G1 X132.109 Y99.148 E.0439
M73 P46 R0
M73 Q46 S0
G1 X143.813 Y110.852 E.84092
G1 X142.949 Y110.852 E.0439
M73 P47 R0
M73 Q47 S0
G1 X131.245 Y99.148 E.84092
G1 X130.381 Y99.148 E.0439
M73 P48 R0
M73 Q48 S0
G1 X142.085 Y110.852 E.84092
G1 X141.221 Y110.852 E.0439
M73 P49 R0
M73 Q49 S0
G1 X129.517 Y99.148 E.84092
G1 X128.653 Y99.148 E.0439
M73 P50 R0
M73 Q50 S0
G1 X140.357 Y110.852 E.84092
M73 Q51 S0
G1 X139.493 Y110.852 E.0439
M73 P51 R0
M73 Q52 S0
G1 X127.789 Y99.148 E.84092
G1 X126.925 Y99.148 E.0439
M73 P52 R0
M73 Q53 S0
G1 X138.629 Y110.852 E.84092
G1 X137.765 Y110.852 E.0439
M73 P53 R0
M73 Q54 S0
G1 X126.061 Y99.148 E.84092
G1 X125.197 Y99.148 E.0439
M73 P54 R0
M73 Q55 S0
G1 X136.9 Y110.852 E.84088
G1 X136.036 Y110.852 E.0439
M73 P55 R0
M73 Q56 S0
G1 X124.333 Y99.148 E.84088
M73 P56 R0
G1 X123.468 Y99.148 E.04395
M73 P57 R0
M73 Q57 S0
G1 X135.172 Y110.852 E.84092
G1 X134.308 Y110.852 E.0439
M73 P58 R0
M73 Q58 S0
G1 X122.604 Y99.148 E.84092
G1 X121.74 Y99.148 E.0439
M73 P59 R0
M73 Q59 S0
G1 X133.444 Y110.852 E.84092
G1 X132.58 Y110.852 E.0439
M73 P60 R0
M73 Q60 S0
G1 X120.876 Y99.148 E.84092
G1 X120.012 Y99.148 E.0439
M73 P61 R0
M73 Q61 S0
G1 X131.716 Y110.852 E.84092
G1 X130.852 Y110.852 E.0439
M73 P62 R0
M73 Q62 S0
G1 X119.148 Y99.148 E.84092
G1 X118.284 Y99.148 E.0439
M73 P63 R0
M73 Q63 S0
G1 X129.988 Y110.852 E.84092
G1 X129.124 Y110.852 E.0439
M73 P64 R0
M73 Q64 S0
G1 X117.42 Y99.148 E.84092
G1 X116.556 Y99.148 E.0439
M73 P65 R0
M73 Q65 S0
G1 X128.26 Y110.852 E.84092
G1 X127.396 Y110.852 E.0439
M73 P66 R0
M73 Q66 S0
G1 X115.692 Y99.148 E.84092
G1 X114.828 Y99.148 E.0439
M73 P67 R0
M73 Q67 S0
G1 X126.531 Y110.852 E.84088
G1 X125.667 Y110.852 E.0439
M73 P68 R0
M73 Q68 S0
G1 X113.964 Y99.148 E.84088
G1 X113.099 Y99.148 E.04395
M73 P69 R0
M73 Q69 S0
G1 X124.803 Y110.852 E.84092
M73 Q70 S0
G1 X123.939 Y110.852 E.0439
M73 P70 R0
M73 Q71 S0
G1 X112.235 Y99.148 E.84092
G1 X111.371 Y99.148 E.0439
M73 P71 R0
M73 Q72 S0
G1 X123.075 Y110.852 E.84092
G1 X122.211 Y110.852 E.0439
M73 P72 R0
M73 Q73 S0
G1 X110.507 Y99.148 E.84092
M73 P73 R0
G1 X109.643 Y99.148 E.0439
M73 P74 R0
M73 Q74 S0
G1 X121.347 Y110.852 E.84092
G1 X120.483 Y110.852 E.0439
M73 P75 R0
M73 Q75 S0
G1 X108.779 Y99.148 E.84092
G1 X107.915 Y99.148 E.0439
M73 P76 R0
M73 Q76 S0
G1 X119.619 Y110.852 E.84092
G1 X118.755 Y110.852 E.0439
M73 P77 R0
M73 Q77 S0
G1 X107.051 Y99.148 E.84092
G1 X106.187 Y99.148 E.0439
M73 P78 R0
M73 Q78 S0
G1 X117.891 Y110.852 E.84092
G1 X117.027 Y110.852 E.0439
M73 P79 R0
M73 Q79 S0
G1 X105.323 Y99.148 E.84092
G1 X104.459 Y99.148 E.0439
M73 P80 R0
M73 Q80 S0
G1 X116.162 Y110.852 E.84088
G1 X115.298 Y110.852 E.0439
M73 P81 R0
M73 Q81 S0
G1 X103.595 Y99.148 E.84088
G1 X102.73 Y99.148 E.04395
M73 P82 R0
M73 Q82 S0
G1 X114.434 Y110.852 E.84092
G1 X113.57 Y110.852 E.0439
M73 P83 R0
M73 Q83 S0
G1 X101.866 Y99.148 E.84092
G1 X101.648 Y99.148 E.01108
M73 P84 R0
M73 Q84 S0
G1 X101.648 Y99.794 E.03282
G1 X112.706 Y110.852 E.7945
G1 X111.842 Y110.852 E.0439
M73 P85 R0
M73 Q85 S0
G1 X101.648 Y100.658 E.73243
G1 X101.648 Y101.522 E.0439
M73 P86 R0
M73 Q86 S0
G1 X110.978 Y110.852 E.67035
G1 X110.114 Y110.852 E.0439
M73 P87 R0
M73 Q87 S0
G1 X101.648 Y102.386 E.60827
G1 X101.648 Y103.25 E.0439
M73 P88 R0
M73 Q88 S0
G1 X109.25 Y110.852 E.54619
G1 X108.386 Y110.852 E.0439
G1 X101.648 Y104.114 E.48412
M73 Q89 S0
G1 X101.648 Y104.978 E.0439
M73 P89 R0
G1 X107.522 Y110.852 E.42204
G1 X106.658 Y110.852 E.0439
M73 P90 R0
M73 Q90 S0
G1 X101.648 Y105.842 E.35996
G1 X101.648 Y106.707 E.04395
G1 X105.793 Y110.852 E.29781
G1 X104.929 Y110.852 E.0439
M73 P91 R0
M73 Q91 S0
G1 X101.648 Y107.571 E.23574
G1 X101.648 Y108.435 E.0439
G1 X104.065 Y110.852 E.17366
G1 X103.201 Y110.852 E.0439
G1 X101.648 Y109.299 E.11158
G1 X101.648 Y110.163 E.0439
G1 X102.61 Y111.125 E.06912
M204 S1000
; stop printing object Shape-Box id:0 copy 0
;WIPE_START
G1 F8640;_WIPE
M73 P92 R0
M73 Q92 S0
G1 X101.648 Y110.163 E-.31414
G1 F8640;_WIPE
G1 X101.648 Y109.299 E-.1995
G1 F8640;_WIPE
G1 X102.525 Y110.176 E-.28636
;WIPE_END
G1 Z.6 F720
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z1.2 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z49.2 F720 ; Move print head further up
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 ; disable motors
; max_layer_z = 0.2
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 89.71
; filament used [cm3] = 0.22
; filament used [g] = 0.27
; filament cost = 0.01
; total filament used [g] = 0.27
; total filament cost = 0.01
; estimated printing time (normal mode) = 1m 23s
; estimated printing time (silent mode) = 1m 23s
; estimated first layer printing time (normal mode) = 1m 23s
; estimated first layer printing time (silent mode) = 1m 23s

; prusaslicer_config = begin
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.6
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600\nG1 E0.5 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.6";"nozzle_diameter[0]!=0.8 and printer_notes!~/.*PG.*/ and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.30mm QUALITY @0.6 nozzle MK3
; deretract_speed = 25
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.65
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.65
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 36.29
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusament PLA"
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.65
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 15
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.65
; infill_first = 0
; infill_overlap = 15%
; infill_speed = 70
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.4
; max_print_height = 210
; max_print_speed = 100
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.15
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.6
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{nozzle_diameter[initial_tool]}n_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.65
; perimeter_generator = arachne
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm DETAIL @0.6 nozzle MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+ 0.6 nozzle
; printer_technology = FFF
; printer_variant = 0.6
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 10
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.65
; solid_infill_speed = 70
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.12.2 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.22
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.55
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.3
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 80%
; support_tree_angle = 40
; support_tree_angle_slow = 30
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 3
; support_tree_branch_diameter_double_wall = 0
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.6
; support_tree_top_rate = 30%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 8
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.6
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 45
; top_solid_layers = 5
; top_solid_min_thickness = 0.9
; travel_acceleration = 0
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
