#!/bin/bash

T=tmp.$$.scad
SCAD=/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD

B='zblock iblock jblock oblock tblock bblock dblock fblock magblock magblock_cover base1 base rocker tray tray4 all_cubes'

for i in $B;do
    echo $i...
    rm -f $T
    (cat cubes.scad;echo;echo;echo "$i();") >$T
    $SCAD -o $i.stl $T
    rm -f $T
done

