#!/bin/sh
# generate a catalog of image files
# usage: mk_image_catalog image-files...
n=-1
H=00-catalog.html
echo >$H '<!DOCTYPE html>'
echo >>$H '<html>'
echo >>$H '<head>'
echo >>$H '<style>'
echo >>$H 'th, td {'
echo >>$H '  border-style:solid;'
echo >>$H '  border-color: #96D4D4;'
echo >>$H '}'
echo >>$H '</style>'
echo >>$H '</head>'
echo >>$H '<body>'
echo >>$H '<table>'
echo >>$H '  <tr>'
for i in "$@"; do
  n=`expr $n + 1`
  if test $n = 4; then
      n=0
      echo >>$H '  </tr>'
      echo >>$H '  <tr>'
  fi
  echo >>$H '    <td>'
  echo >>$H '      <a href="'$i'">'
  echo >>$H '      '$(basename $i)'<br><img width="200" height="200" src="'"$i"'">'
  echo >>$H '      </a>'
  echo >>$H '    </td>'
done
echo >>$H '  </tr>'
echo >>$H '</table>'
echo >>$H '</body>'
echo >>$H '</html>'
